### ISSUE TITLE
Where to find API documentation reference?

### ISSUE THREAD

**Issue by yanpanlau** [jvkersch/hsmmlearn#19]
Hi, I am trying to find the API documentation reference. I google it and found the following link

http://hsmmlearn.readthedocs.io/en/latest/source/reference.html

But the API reference is empty. Can you point to me the right link?

Thanks,

Ben

**Comment by jvkersch** [comment]
@yanpanlau Thanks for reporting this. I configured the project to install properly on RTD, and I refreshed the docs build. The api doc should now be available at the link you posted, so I'll close this issue. Please report any further issues or suggestions! Thanks again.
