### ISSUE TITLE
Import error when running "python setup.py develop"

### ISSUE THREAD

**Issue by RenqinCai** [jvkersch/hsmmlearn#26]
ImportError: No module named cython.build

**Comment by jvkersch** [comment]
@RenqinCai You need Cython to be installed in your environment; `pip install cython` (or `conda install cython`, whatever is appropriate for your setup) should do the trick.

**Comment by RenqinCai** [comment]
I think I have installed Cython. This is what I got when I run the command "pip install -r requirements.txt ". Is there anything else that I miss? thanks.
pip install -r requirements.txt 
Requirement already satisfied: cython>=0.22.0 in /Users/jetcai1900/Documents/venv4Python3/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: numpy>=1.9.2 in /Users/jetcai1900/Documents/venv4Python3/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: scipy>=0.15.0 in /Users/jetcai1900/Documents/venv4Python3/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: six>=1.7.0 in /Users/jetcai1900/Documents/venv4Python3/lib/python3.5/site-packages (from -r requirements.txt (line 4))

**Comment by jvkersch** [comment]
@RenqinCai This fell between the cracks, apologies. Can you post the entire traceback for me, when you run `python setup.py develop`?

**Comment by jvkersch** [comment]
Closing as stale
