### ISSUE TITLE
how to predict the hidden states?

### ISSUE THREAD

**Issue by mo10** [jvkersch/hsmmlearn#38]
Hi,
How to predict the hidden state like [this](http://hmmlearn.readthedocs.io/en/latest/tutorial.html#training-hmm-parameters-and-inferring-the-hidden-states)? Is there an example?

Thank you.

**Comment by jvkersch** [comment]
@mo10 Does this fit your use-case: https://hsmmlearn.readthedocs.io/en/latest/source/tutorial.html ?

The api matches that of hmmlearn and scikit-learn to some extent, but please let me know if anything is missing or difficult to use.
