### ISSUE TITLE
Could you tell me which paper you referred to to write this algorithm?

### ISSUE THREAD

**Issue by Wusir2018** [jvkersch/hsmmlearn#44]
Hello,
Could you tell me which paper you referred to to write this algorithm?
I have some questions about the EM algorithm.

Given the sequence of observations, we use the EM algorithm to estimate the parameters of the HSMM model. In the EM algorithm, we first need to give the initial value, and then iterate through the EM algorithm to get the optimal value.

The first step: we use the following code, this code gives the real value of `tmat`, `means`, `scales`, `durations` and other HSMM parameters to get the observation sequence and hidden sequence.
![true](https://user-images.githubusercontent.com/51500032/65601456-b1c43f00-dfd4-11e9-991b-35588a5c9451.png)

The second step: use the EM algorithm to solve the parameters of the HSMM model. Firstly, give the hypothetical initial values of the `new_tmat`, `new_means`, `new_scales`, and `new_durations` parameters, and then use the `hsmm.fit` function to train our observation sequence to obtain the parameters of the HSMM. Are the parameters obtained in this step approximate to the real values?
![fit](https://user-images.githubusercontent.com/51500032/65601466-b852b680-dfd4-11e9-8291-3897086b3263.png)

**Comment by jvkersch** [comment]
@Wusir2018 The paper is Y. Guedon (2003), Estimating Hidden Semi-Markov chains from Discrete Sequences. JCGS 12 (3), pp. 604-639.
